name: Access server
on: push
jobs:
  access_server:
    name: Access server
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get -y update
            cd django_project/django-deployment-guide
            ls
            git pull origin main
            docker ps -a
            docker stop my-python-app  # Stop the existing container
            docker rm my-python-app    # Remove the existing container
            docker rmi my-python-app:1.0  # Remove the existing image (if needed)
            docker build -t my-python-app:1.0 .
            docker run -p 8000:8000 my-python-app:1.0
